[package]
name = "cargo-onedoc"
version = "0.2.2"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2021"
description = "Generate your README.md from Rust doc comments"
readme = "README.md"
repository = "https://github.com/rossmacarthur/cargo-onedoc"
license = "MIT OR Apache-2.0"
keywords = ["readme", "markdown", "documentation", "cargo"]
categories = ["development-tools::cargo-plugins"]
include = ["src/**/*", "LICENSE-*", "README.md"]

[dependencies]
anyhow = "1.0.86"
camino = "1.1.7"
cargo_metadata = "0.19.2"
casual = "0.2.0"
constcat = "0.6.0"
pulldown-cmark = "0.11.0"
pulldown-cmark-to-cmark = "15.0.1"
pulldown-cmark-toc = "0.5.0"
regex-macro = "0.3.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.20"
upon = "0.9.0"

[dependencies.clap]
version = "4.5.8"
default-features = false
features = [
    "std", "help", "usage", "error-context", "suggestions", # default excluding "color"
    "cargo", "env", "derive"                                # optional
]

[dev-dependencies]
pretty_assertions = "1.4.1"
