//! 📝 Generate README.md from doc comments.
//!
//! Only write your documentation once! This crate provides a Cargo subcommand
//! that can generate Markdown files from your Rust doc comments.

mod fix;
mod render;

use std::fs;
use std::io;

use anyhow::{anyhow, Context as _, Result};
use camino::Utf8Path as Path;
use cargo_metadata::Package;
use clap::Parser as _;
use pulldown_cmark::{Options, Parser};

#[derive(Debug, clap::Parser)]
#[clap(
    name = "cargo",
    bin_name = "cargo",
    disable_help_subcommand(true),
    subcommand_required(true)
)]
enum Cargo {
    #[clap(name = "onedoc")]
    Command(Opt),
}

#[derive(Debug, clap::Args)]
#[command(author, version, about)]
struct Opt {
    #[clap(long)]
    check: bool,
}

fn main() -> Result<()> {
    let Cargo::Command(opt) = Cargo::parse();

    let mut engine = upon::Engine::new();
    engine.add_template("readme", include_str!("README_TEMPLATE.md"))?;
    engine.add_filter("trim_prefix", |s: &str, p: &str| {
        s.trim_start_matches(p).to_owned()
    });

    let metadata = cargo_metadata::MetadataCommand::new().exec()?;
    let pkg = metadata.root_package().context("no root package")?;
    generate(opt.check, &engine, pkg)?;

    Ok(())
}

fn generate(check: bool, engine: &upon::Engine, pkg: &Package) -> Result<()> {
    let output = pkg.readme().context("no readme path in package manifest")?;

    let input = get_input_path(pkg)?;

    let text =
        get_module_comment(input).with_context(|| format!("failed to read from `{}`", &input))?;
    let mut events = Vec::from_iter(Parser::new_ext(&text, Options::all()));

    // apply fixups
    events = fix::headings(events);
    events = fix::code_blocks(events).context("failed to fix codeblocks")?;
    events = fix::links(events);

    // render contents as markdown
    let contents = render::to_cmark(&events).context("failed to render contents")?;

    let mut rendered = engine
        .get_template("readme")
        .unwrap()
        .render(upon::value! {
            manifest: pkg,
            contents: contents,
        })
        .map_err(|e| anyhow!("{:#}", e))?;
    rendered.insert_str(0, "<!-- Generated by cargo-onedoc. DO NOT EDIT. -->\n\n");

    let dir = pkg.manifest_path.parent().unwrap();
    let current = match fs::read_to_string(&output) {
        Ok(c) => c,
        Err(err) if err.kind() == io::ErrorKind::NotFound => String::new(),
        Err(err) => return Err(err).context("failed to read current README")?,
    };
    if current == rendered {
        println!(
            "{} -> {} is up to date",
            input.strip_prefix(dir).unwrap(),
            output.strip_prefix(dir).unwrap(),
        );
    } else if check {
        println!(
            "{} -> {} is out of date",
            input.strip_prefix(dir).unwrap(),
            output.strip_prefix(dir).unwrap(),
        );
    } else {
        fs::write(&output, rendered)
            .with_context(|| format!("failed to write to `{}`", &output))?;
        println!(
            "{} -> {} was updated",
            input.strip_prefix(dir).unwrap(),
            output.strip_prefix(dir).unwrap(),
        );
    }

    Ok(())
}

fn get_input_path(pkg: &Package) -> Result<&Path> {
    if let Some(t) = pkg
        .targets
        .iter()
        .find(|t| t.kind.iter().any(|k| k == "lib"))
    {
        return Ok(&t.src_path);
    }

    if let Some(t) = pkg
        .targets
        .iter()
        .find(|t| t.kind.iter().any(|k| k == "bin"))
    {
        return Ok(&t.src_path);
    }

    Err(anyhow!(
        "failed to determine default source file for package"
    ))
}

fn get_module_comment(path: &Path) -> Result<String> {
    let contents = fs::read_to_string(path)?;
    let lines: Vec<_> = contents
        .lines()
        .take_while(|line| line.starts_with("//!"))
        .map(|line| line.trim_start_matches("//! ").trim_start_matches("//!"))
        .collect();
    Ok(lines.join("\n"))
}
