mod config;
mod fix;
mod render;

use std::collections::BTreeMap;
use std::fs;
use std::io;

use anyhow::{Context as _, Result, anyhow, bail};
use camino::Utf8Path as Path;
use cargo_metadata::Package;
use clap::Parser as _;
use constcat::concat;
use pulldown_cmark::HeadingLevel;
use pulldown_cmark::{Options, Parser};
use pulldown_cmark_toc as toc;
use regex_macro::{LazyRegex, lazy_regex};

use crate::config::{Config, Doc};

const VERSION: &str = env!("CARGO_PKG_VERSION");

const HEADER: &str = concat!(
    "<!-- Generated by cargo-onedoc v",
    VERSION,
    ". DO NOT EDIT. -->\n\n"
);

static HEADER_REGEX: LazyRegex =
    lazy_regex!(r"^<!-- Generated by cargo-onedoc v(.*)\. DO NOT EDIT\. -->\n\n");

#[derive(Debug, clap::Parser)]
#[clap(
    name = "cargo",
    bin_name = "cargo",
    disable_help_subcommand(true),
    subcommand_required(true)
)]
enum Cargo {
    #[clap(name = "onedoc")]
    Command(Opt),
}

#[derive(Debug, Clone, clap::Args)]
#[command(author, version, about)]
struct Opt {
    /// The package to generate the files for
    #[clap(long, short)]
    package: Option<String>,

    /// Check if the file(s) are up to date instead of updating them
    #[clap(long)]
    check: bool,

    /// Do not prepend the "Generated by cargo-onedoc" header
    #[clap(long)]
    no_header: bool,

    /// Force write by bypassing any "overwrite?" prompts.
    #[clap(long)]
    force: bool,
}

pub struct Context<'a> {
    check: bool,
    no_header: bool,
    force: bool,
    package: Option<&'a Package>,
    config: Config,
}
fn main() -> Result<()> {
    let Cargo::Command(Opt {
        check,
        package,
        no_header,
        force,
    }) = Cargo::parse();
    let metadata = cargo_metadata::MetadataCommand::new().exec()?;

    let pkg = match package {
        Some(name) => metadata
            .workspace_packages()
            .into_iter()
            .find(|p| p.name.as_ref() == name)
            .ok_or_else(|| anyhow!("package `{}` not found in workspace", name))?,
        None => metadata.root_package().context("no root package")?,
    };

    let config = config::load(&metadata, pkg)?;
    generate_all(Context {
        check,
        no_header,
        force,
        package: Some(pkg),
        config,
    })
}

fn generate_all(ctx: Context<'_>) -> Result<()> {
    let mut engine = {
        let mut e = upon::Engine::new();
        e.add_function("trim_prefix", |s: &str, p: &str| {
            s.trim_start_matches(p).to_owned()
        });
        e
    };

    for doc in &ctx.config.docs {
        generate_doc(&mut engine, &ctx, doc)?;
    }
    Ok(())
}

#[derive(Clone, Copy)]
enum Kind {
    RustDoc,
    Markdown,
}

type Links = BTreeMap<String, Vec<String>>;

fn generate_doc(engine: &mut upon::Engine<'_>, ctx: &Context<'_>, doc: &Doc) -> Result<()> {
    // Compile the template
    let template_name = match &doc.template {
        Some(path) => {
            let contents = fs::read_to_string(path)?;
            engine
                .add_template(path.to_string(), contents)
                .map_err(|e| anyhow!("{:#}", e))?;
            path.to_string()
        }
        None => {
            let name = "<anonymous>";
            engine
                .add_template(name, include_str!("README_TEMPLATE.md"))
                .map_err(|e| anyhow!("{:#}", e))?;
            name.to_string()
        }
    };

    // Load the Markdown to process
    let to_process = {
        let mut items = Vec::new();
        for input in &doc.inputs {
            let item = match input.extension() {
                Some("rs") => {
                    let kind = Kind::RustDoc;
                    let text = get_module_comment(input)
                        .with_context(|| format!("failed to read from `{input}`"))?;
                    (kind, text)
                }
                Some("md") => {
                    let kind = Kind::Markdown;
                    let text = fs::read_to_string(input)
                        .with_context(|| format!("failed to read from `{input}`"))?;
                    (kind, text)
                }
                Some(_) | None => {
                    bail!("unsupported file extension `{}`", input);
                }
            };
            items.push(item);
        }
        items
    };

    let rendered = render(engine, ctx, &template_name, to_process)?;

    let current = match fs::read_to_string(&doc.output) {
        Ok(c) => Some(c),
        Err(err) if err.kind() == io::ErrorKind::NotFound => None,
        Err(err) => return Err(err).context("failed to read current README")?,
    };

    enum Action {
        Skip,
        Update(String),
    }

    let action = if ctx.no_header {
        match current.as_ref() == Some(&rendered) {
            true => Action::Skip,
            false => Action::Update(rendered),
        }
    } else {
        let mut action = match current.as_deref() {
            Some(current) => {
                // Check if there is a header, if there isn't then we should
                // first confirm the user really wants to overwrite the file.
                match HEADER_REGEX.captures(current) {
                    Some(caps) => {
                        // Check is header is a compatible version, if the rest
                        // of the document matches then we won't update the
                        // header version.
                        let header = caps.get(0).unwrap().as_str();
                        let current = &current[header.len()..];
                        let req = semver::VersionReq::parse(&caps[1]).ok();
                        let version = semver::Version::parse(VERSION).unwrap();
                        match (req, version) {
                            (Some(req), ours) if req.matches(&ours) => match current == rendered {
                                true => Action::Skip,
                                false => Action::Update(rendered),
                            },
                            _ => {
                                if !ctx.check
                                    && !ctx.force
                                    && !casual::confirm(format!(
                                        "{} was generated by an incompatible version of cargo-onedoc.\nDo you want to overwrite it?",
                                        &doc.output
                                    ))
                                {
                                    bail!("Aborted!")
                                }
                                Action::Update(rendered)
                            }
                        }
                    }
                    None => {
                        if !ctx.check
                            && !ctx.force
                            && !casual::confirm(format!(
                                "{} was not generated by cargo-onedoc.\nDo you want to overwrite it?",
                                &doc.output
                            ))
                        {
                            bail!("Aborted!")
                        }
                        Action::Update(rendered)
                    }
                }
            }
            None => Action::Update(rendered),
        };

        if let Action::Update(rendered) = &mut action {
            rendered.insert_str(0, HEADER);
        }

        action
    };

    match action {
        Action::Skip => {
            println!("{} is up to date", &doc.output);
        }
        Action::Update(_) if ctx.check => {
            bail!("{} is out of date", &doc.output);
        }
        Action::Update(rendered) => {
            fs::write(&doc.output, rendered)
                .with_context(|| format!("failed to write to `{}`", &doc.output))?;
            println!("{} was updated", &doc.output);
        }
    }

    Ok(())
}

fn get_module_comment(path: &Path) -> Result<String> {
    let contents = fs::read_to_string(path)?;
    let lines: Vec<_> = contents
        .lines()
        .take_while(|line| line.starts_with("//!"))
        .map(|line| line.trim_start_matches("//! ").trim_start_matches("//!"))
        .collect();
    Ok(lines.join("\n"))
}

/// Renders the contents excluding the header.
fn render(
    engine: &upon::Engine<'_>,
    ctx: &Context,
    template_name: &str,
    to_process: Vec<(Kind, String)>,
) -> Result<String> {
    let mut events = Vec::new();
    let mut link_config = Links::new();

    for (kind, text) in &to_process {
        let mut es = Vec::from_iter(Parser::new_ext(text, Options::all()));
        // common fixes
        es = fix::headings(es);
        match kind {
            Kind::RustDoc => {
                es = fix::code_blocks(es).context("failed to fix code blocks")?;
                es = fix::doc_links(&ctx.config, &mut link_config, es);
            }
            Kind::Markdown => {
                es = fix::rel_links(&ctx.config, es);
            }
        }
        events.extend(es);
    }

    // Now render contents as markdown
    let full_contents = render::to_cmark(&events).context("failed to render contents")?;

    let (summary, contents) = {
        let (s, c) = fix::summary(events);
        let summary = render::to_cmark(&s).context("failed to render summary")?;
        let contents = render::to_cmark(&c).context("failed to render contents")?;
        (summary, contents)
    };

    let toc = toc::TableOfContents::new(&full_contents)
        .to_cmark_with_options(toc::Options::default().levels(HeadingLevel::H2..=HeadingLevel::H6));

    let rendered = engine
        .get_template(template_name)
        .unwrap()
        .render(upon::value! {
            config: &ctx.config,
            manifest: ctx.package,
            summary: summary,
            contents: contents,
            full_contents: full_contents,
            toc: toc,
        })
        .to_string()
        .map_err(|e| anyhow!("{:#}", e))?;

    Ok(rendered)
}

#[cfg(test)]
mod tests {
    use super::*;

    use pretty_assertions::assert_eq;

    fn quick_render(
        config: &str,
        to_process: impl IntoIterator<Item = (Kind, &'static str)>,
    ) -> Result<String> {
        let engine = {
            let mut e = upon::Engine::new();
            e.add_template("README.md", "{{ summary }}\n{{ contents }}")?;
            e
        };
        let to_process = Vec::from_iter(to_process.into_iter().map(|(k, s)| (k, s.to_owned())));
        let ctx = Context {
            check: false,
            no_header: true,
            force: false,
            package: None,
            config: toml::from_str(config).unwrap(),
        };
        render(&engine, &ctx, "README.md", to_process)
    }

    #[test]
    fn test_rustdoc_fix_code_blocks() {
        let doc = "```\npanic!()\n```\n";
        let expected = "\n```rust\npanic!()\n```\n";
        let result = quick_render("", [(Kind::RustDoc, doc)]).unwrap();
        assert_eq!(expected, result);
    }

    #[test]
    fn test_rustdoc_fix_doc_links() {
        let config = r#"
[links]
"bar" = "https://example.com/foo/bar"
"#;
        let doc = "\nHere is [`bar`]\n";
        let expected = "Here is [`bar`][bar]\n\n\
                        [bar]: https://example.com/foo/bar\n";

        let result = quick_render(config, [(Kind::RustDoc, doc)]).unwrap();
        assert_eq!(expected, result);
    }

    #[test]
    fn test_rustdoc_fix_doc_links_unprocessed() {
        let config = "";
        let doc = "\nHere is [`bar`]\n";
        let expected = "Here is `bar`\n";

        let result = quick_render(config, [(Kind::RustDoc, doc)]).unwrap();
        assert_eq!(expected, result);
    }

    #[test]
    fn test_rustdoc_fix_doc_links2() {
        let config = r#"
[links]
"bar" = "https://example.com/foo/bar"
"#;
        let doc = "\nHere is [`bar`]\n\n[`bar`]: foo::bar";
        let expected = "Here is [`bar`][bar]\n\n\
                        [bar]: https://example.com/foo/bar\n";

        let result = quick_render(config, [(Kind::RustDoc, doc)]).unwrap();
        assert_eq!(expected, result);
    }

    #[test]
    fn test_rustdoc_fix_doc_links2_unprocessed() {
        let config = "";
        let doc = "\nHere is [`bar`][bar]\n";
        let expected = "Here is `bar`\n";

        let result = quick_render(config, [(Kind::RustDoc, doc)]).unwrap();
        assert_eq!(expected, result);
    }

    #[test]
    fn test_rustdoc_fix_doc_links3() {
        let config = r#"
[links]
"foo::bar" = "https://example.com/foo/bar"
"#;
        let doc = "\nHere is [`bar`][foo::bar]\n";
        let expected = "Here is [`bar`][foo::bar]\n\n\
                        [foo::bar]: https://example.com/foo/bar\n";

        let result = quick_render(config, [(Kind::RustDoc, doc)]).unwrap();
        assert_eq!(expected, result);
    }

    #[test]
    fn test_rustdoc_fix_doc_links3_unprocessed() {
        let config = "";
        let doc = "\nHere is [`bar`][foo::bar]\n";
        let expected = "Here is `bar`\n";

        let result = quick_render(config, [(Kind::RustDoc, doc)]).unwrap();
        assert_eq!(expected, result);
    }

    #[test]
    fn test_markdown_fix_rel_link() {
        let config = r#"
[links]
"bar.md" = "https://example.com/bar"
"#;
        let md = r#"
Here is [foo](bar.md#foo)

Here is [foo]
Here is [bar][foo]

[foo]: bar.md#foo
"#;
        let expected = r#"Here is [foo](https://example.com/bar#foo)
Here is [foo]
Here is [bar][foo]

[foo]: https://example.com/bar#foo"#;

        let result = quick_render(config, [(Kind::Markdown, md)]).unwrap();
        assert_eq!(expected, result);
    }
}
